### ISSUE TITLE
Create build system for frontend

### ISSUE THREAD

**Issue by EdenSG** [xSke/Pxls#12]
This would:
1. make for easier local development
2. make the site load a little faster, and use less bandwidth

**Comment by EdenSG** [comment]
I'll play around a bit and try to make something that's super easy to set up and use

**Comment by wblondel** [comment]
Or at least a README...

**Comment by EdenSG** [comment]
@wblondel that's #2

**Comment by xSke** [comment]
Made Maven minify files before building the final .jar, is this what you mean?

**Comment by EdenSG** [comment]
No, I'm talking about some kind of optimization/minification for the front-end. Perhaps setting up webpack or gulp would work - I'm referring to running the css through Autoprefixer and a minifier, the js through a minifier, and allowing you to change what host the js uses for interacting with the backend (either in a config file or via an environment variable).

**Comment by gunnerwolf** [comment]
Maven is already setup to minify the front-end files (js and css) during build.
