### ISSUE TITLE
Set up SSL certificate

### ISSUE THREAD

**Issue by EdenSG** [xSke/Pxls#15]
[Come August, desktop notifications will no longer work in Chrome unless we have an SSL cert](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

[Here's how to get the keys and certs you need](https://certbot.eff.org/#debianjessie-other).

**Comment by Sorunome** [comment]
Websockets and stuff could be proxied via nginx, so the java server would actually need no modification for this

**Comment by Sorunome** [comment]
Close since the site works under https now?

**Comment by EdenSG** [comment]
Sure, I suppose. That said, I would still prefer to have the site use https by default (i.e. redirect the http version to https)
