### ISSUE TITLE
Feature: Pixel Accumlation

### ISSUE THREAD

**Issue by Sbrown-WilliamsCrusher** [xSke/Pxls#17]
This has been talked about alot in the dev channel on discord.
Heres the general idea
> Fracta (r/parahumans 626,483) - Today at 2:57 PM
For every [cooldown time] minutes, you get an extra pixel, so you can use a bunch at once. To stop people leaving their machine running overnight and then griefing, have a maximum number of pixels you can accumulate, perhaps 10 or so. That way, you can go off and do something else, then come back and make a huge leap of progress or fix damage quickly.(edited)

Please leave thoughts and ideas. or react to this

**Comment by brandonsturgeon** [comment]
This would allow a group of 10 people to place 100 pixels all at once. This gives griefers great potential to really wipe something out very quickly.

pxls.space doesn't suffer from griefers as much as r/place did, so maybe this is less of an issue.

**Comment by TheRebelG0d** [comment]
Implemented in 8b478155c77e3d5e37316b1be14f2d74f7e64b6d
