### ISSUE TITLE
How do you change the environment variables?

### ISSUE THREAD

**Issue by ki4jgt** [xSke/Pxls#19]
I've tried appending -port to mavan. I've tried editing pom.xml. The port isn't changing for me. It's stuck on 4567. I'm new to mvn.

**Comment by xSke** [comment]
Not sure how it works on Windows, but  on Linux you just type "export PORT=2345" (etc) before starting the server.

**Comment by TopFuel** [comment]
On Windows is "set PORT=2345" before you start the server.
