### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by wblondel** [xSke/Pxls#2]
Hi!

Please write a README so that we know how to deploy the website :D

**Comment by Sbrown-WilliamsCrusher** [comment]
PreReq: Java 8,Maven,Recaptcha api key

git clone http://github.com/xSke/Pxls
cd Pxls
add api key to Pxls/resources/public/index.html
mvn clean package 
java -jar target/pxls-1.0-SNAPSHOT.jar

**Comment by xSke** [comment]
Added one.
