### ISSUE TITLE
How is the dat file formatted?

### ISSUE THREAD

**Issue by ki4jgt** [xSke/Pxls#22]
Let's say I wanted to translate a .bmp file into a .dat file (using Python). . . what format does the .dat file follow?

**Comment by Kefta** [comment]
Not really related to the repository -- just took a simple google search: http://www.u.arizona.edu/~kforster/dmastr/dm_man4.htm

**Comment by xSke** [comment]
The link linked above is completely irrelevant - `.dat` is just a general extension for a data file. The pxls board data is simply a byte array of [width*height], each byte being an index into the palette.
