### ISSUE TITLE
Issue with SQL now(6)

### ISSUE THREAD

**Issue by Ukicu** [xSke/Pxls#29]
I'm good with java but I don't know much about sql... I keep getting this error when I run, it seems to have some issue with the timestamp default value now(6).
![issue](https://cloud.githubusercontent.com/assets/16504868/24913309/bd8f521a-1e9e-11e7-9ade-c1c2aaa413a1.PNG)
![issue2](https://cloud.githubusercontent.com/assets/16504868/24913313/c082e496-1e9e-11e7-82d8-ce1973a537b2.PNG)
Am I doing something wrong?
Edit: it was also having issues with the board.dat file. It was not created automatically and I got errors for it, so I made it manually and left it empty. I don't know if that has anything to do with it.

**Comment by Sorunome** [comment]
Your mariadb version is likely out-of-date, what does `mysql --version` give you?

And the board.dat file is created automatically if SQL is working correctly. If you create board.dat manually it will just lead to more errors down the road

**Comment by Ukicu** [comment]
Thanks a ton! I could have sworn I tried that, but sure enough I updated again and it worked fine. Thanks!
