### ISSUE TITLE
Invisible reCAPTCHA

### ISSUE THREAD

**Issue by Ameliorate** [xSke/Pxls#3]
In your comments, you said you were opposed to a CAPTCHA because it would be too invasive for users to complete a CAPTCHA every time they want to fill in a pixel. This is not actually the case. Google provides an [Invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/versions#invisible) that only pops up if Google suspects you are a bot. Calling this when placing a pixel will provide a transparent user experience while also preventing botting.

**Comment by Lenni** [comment]
I would argue that some paintings can only be accomplished with a Bot. Therefore I See no Rayon to actively prevent Botting

**Comment by Ameliorate** [comment]
Any painting can be created with a sufficiently dedicated fanbase. An Invisible reCAPTCHA wouldn't prevent userscripts that display a overlay of where to place tiles, and a simple painting would be repaired by passers by who repair a stray pixel or two.

What this would prevent is people leaving their computers on 24/7, preventing new art from being created over old. Humans know when to give up, bots do not.

**Comment by Lenni** [comment]
I agree to your Point, that 24/7 bots should be prevented, but whats I referred to a "Bots" Werne Userscripts. In my eyes the User would be affected by the Captcha, because after a few Funktion Falls Google nicht suspect he is a bot, because he is not acting "human" e.g. moving the mouse inside the webpage etc.

**Comment by Ameliorate** [comment]
Google will usually back off with captchas if they successfully complete a few after being suspected. I think users will much rather solve a few captchas than compete with userscript bots. 

There's no way to differ between userscript bots and 24/7 bots, because you can run a userscript bot all night long. For a human, they have to sleep and eat, putting them at a disadvantage compared to the botters.

**Comment by hjroh0315** [comment]
Invisible ReCAPTCHAs won't do much. The bot could always use a technique to move the cursor smoothly.

**Comment by Ameliorate** [comment]
Google is not dumb enough to be tricked by such a simple technique. A human
will move his mouse in fast, inaccurate movements that are hard to
replicate with a bot. Google uses these movements and other metrics to
detect botting.

**Comment by simon816** [comment]
https://github.com/xSke/Pxls/commit/0d52418ab6faf5a0dafcb8d6ab94b21e893a7ac3
