### ISSUE TITLE
How can I disable reddit or google authorization?

### ISSUE THREAD

**Issue by Jallot** [xSke/Pxls#35]

**Comment by Ukicu** [comment]
I wanted the same thing. Option to disable authentication and captchas?

**Comment by Sorunome** [comment]
Captcha is already disabled by default - it is only enabled if you provide API keys

**Comment by xSke** [comment]
There is currently no way to disable authentication, since the user system is so ingrained into the code.

**Comment by Ukicu** [comment]
Do you ever plan on removing it?
