### ISSUE TITLE
How to get real IP when running Nginx?

### ISSUE THREAD

**Issue by Pitu** [xSke/Pxls#55]
I have the java app running on port 4567, and I'm using nginx to make a reverse proxy to my domain. All I see on the console output is either 127.0.01 or 0:0:0:0:0:0:0:1. My location block on nginx looks like this:

```nginx
location / {
    proxy_read_timeout 3600s;
    proxy_redirect off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-NginX-Proxy true;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_http_version 1.1;
    proxy_pass_request_headers on;
    proxy_set_header Connection "keep-alive";
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'Upgrade';
    proxy_cache_bypass $http_upgrade;
    
    proxy_store off;
    proxy_pass http://localhost:4567;
}
```

But it seems this is not enough. Could anyone point me into the right direction here?

**Comment by jay-bricksoft** [comment]
if the APP says it's from 127.0.0.1 /  0:0:0:0:0:0:0:1, that's because the request came proxied through nginx.
if you expect to see an external ip try using the proxied port directly without nginx' proxy.
if it still logs some unexpected ip, there might be something wrong with your gateway setup.

I'm not the most experienced with nginx but you should set proxy_pass_reverse, so nginx runs as transparent proxy.

hth.

**Comment by Pitu** [comment]
What do you mean by
>try using the proxied port directly without nginx' proxy

As far as I'm aware, I need Apache/Nginx to tie a domain name to a port, or does this java app do some black magic I can take advantage of to do this that I'm unaware?

**Comment by jay-bricksoft** [comment]
nginx works as proxy so you can serve something from another port to the usual port.
e.g. if your app runs on port 9600 you can proxy it to port 80.

in your config you proxy port `4567` to port 80 with address `/`

you can try to access this app directly on port `4567`
then look in your log and check if the adress is still `127.0.0.1`, if so this has to do with misconfiguration of nginx.

detailed answers are here: https://serverfault.com/questions/314574/nginx-real-ip-header-and-x-forwarded-for-seems-wrong/414166

try this fairly plain config:
```
location / {
    proxy_pass http://localhost:4567;
}
```

if this config works, you should overthink your config parameters, which some might be wrong or misplaced.

hth.

**Comment by xSke** [comment]
Check the `server.proxy` block of pxls.conf - it'll allow you to set up a chain of headers to check for a real IP.

**Comment by Pitu** [comment]
@xSke thanks for the reply. I tried with the following items inside the array but I'm still getting only localhost. Am I using the wrong ones here?

```js
proxy {
	localhosts: ["127.0.0.1", "0:0:0:0:0:0:0:1"]
	headers: ['x-forwarded-for', 'X-Forwarded-For', 'X-Real-IP', 'x-real-ip']
}
```

**Comment by Sorunome** [comment]
try `proxy_set_header X-Forwarded-For $remote_addr;`
