### ISSUE TITLE
Allow link to pixel

### ISSUE THREAD

**Issue by TexAgg** [xSke/Pxls#7]
In /r/place you could link directly to a pixel: https://www.reddit.com/r/place/#x=104&y=14 (it doesn't work now that Place has ended). Is it possible to add this?

**Comment by kritixilithos** [comment]
Yes, you can put the location as a query parameter. See here for an example: http://pxls.space/?x=500&y=500

**Comment by xSke** [comment]
As @kritixilithos said, this feature already exists.
