### ISSUE TITLE
On launch, I get an error about a backup file not found. It's my first launch, so IDK what it's trying to do

### ISSUE THREAD

**Issue by thebeastgamer25** [xSke/Pxls#78]

**Comment by gunnerwolf** [comment]
Afaik this is a non-terminating error, so it's more of a warning than an error, It doesn't know whether this is your first launch or not, so it looks for the backup file, and if it doesn't find it, gives you a warning and continues starting up.

Once it's started up it should have created a backup file.

**Comment by Sorunome** [comment]
you have to crate a `backups` folder in the folder you run the java command in
